### ISSUE TITLE
Song stop's mid play?

### ISSUE THREAD

**Issue by MFNich** [nexu-dev/discord.js-music#19]
I know there was another thread on this issue but it didn't seem to get solved. Does anyone know why the bot will just leave the channel mid song?

**Comment by rishord** [comment]
What's the error you're getting? The other thread helped me fixed the problem.

**Comment by MFNich** [comment]
I tried implementing the solution from the other thread.

When  I replace
let dispatcher = connection.playStream(ytdl(video.webpage_url, {filter: 'audioonly'}), {seek: 0, volume: (DEFAULT_VOLUME/100)});
with
let dispatcher = connection.playStream(stream(video.webpage_url))

I get this error:

 throw er; // Unhandled 'error' event
^

TypeError: Invalid non-string/buffer chunk
at validChunk (_stream_writable.js:238:10)
at PassThrough.Writable.write (_stream_writable.js:272:21)
at PassThrough.Writable.end (_stream_writable.js:536:10)
at emitThree (events.js:140:20)
at DestroyableTransform.emit (events.js:216:7)
at emitThree (events.js:135:13)
at FfmpegCommand.emit (events.js:216:7)
at emitEnd (C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\li
b\processor.js:424:16)
at C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\lib\process
or.js:433:16
at C:\Users\Matt\code\project-discord\node_modules\async\dist\async.js:421:1
6

**Comment by Philip-j-fry** [comment]
This happens to me as well plays half of the song then just stops

**Comment by derekmartinez18** [comment]
What version of `node-ytdl` are you using? This was a known issue I discovered as well in an older version. It's referenced [here](https://github.com/fent/node-ytdl-core/issues/81). It should be fine in `0.12.1` and greater.

**Comment by MFNich** [comment]
@derekmartinez18 
I have v 0.17.1  installed. Still haven't found a fix for audio stream stop about 60% through. I tried the solution from the other thread but I receive the error I posted in my previous comment.

**Comment by duart38** [comment]
for me this seems to be the case with only some youtube videos... others it stops mid and some it does not even play at all!! there's an issue on that also 
 see 
#26
