### ISSUE TITLE
Always crashes when trying to play a song.

### ISSUE THREAD

**Issue by PixelGH** [nexu-dev/discord.js-music#21]
Whenever someone tries to play a song, the bot crashes. It doesn't matter if it's looking for youtube/vimeo/whatever or a string. The error is always the same: 

`{ Error: spawn UNKNOWN
    at _errnoException (util.js:1021:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:494:9)
    at exports.execFile (child_process.js:209:15)
    at call (PATH_TO_BOT\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (PATH_TO_BOT\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at msg.channel.sendMessage.then.response (PATH_TO_BOT\node_modules\discord.js-music-v11\index.js:132:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'UNKNOWN', errno: 'UNKNOWN', syscall: 'spawn' }` 

I already tried updating youtube-dl and it changed nothing.

**Comment by PixelGH** [comment]
Appears to be an issue with node youtube-dl.
