### ISSUE TITLE
Playing is broke.

### ISSUE THREAD

**Issue by adelwolf** [nexu-dev/discord.js-music#22]
`{ Error: spawn UNKNOWN
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at call (C:\Users\Neel\adelbot\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\Users\Neel\adelbot\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at msg.channel.sendMessage.then.response (C:\Users\Neel\adelbot\node_modules\discord.js-music-v11\index.js:132:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'UNKNOWN', errno: 'UNKNOWN', syscall: 'spawn' }`

^ is my error, I have no idea how to get around it, as i am kind of noob,

**Comment by willemjanpattyn** [comment]
I managed to make it work by installing specific versions of youtube-dl and ytdl-core.
`npm install youtube-dl@1.11.1`
`npm install ytdl-core@0.9.1`

Works only for YouTube URLs. I found that trying it with other links, it gives a video id not found error. But I suspect it has something to do with one of the above mentioned libraries.
