### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by MarcTheEmperor** [nexu-dev/discord.js-music#8]
I don't know why, if I host it on a server it will not work but when I host it on my PC it works fine, everything and every file is the same.

**Comment by GlitchMasta47** [comment]
What OS is your server on? Sometimes certain OS versions don't work well with ffmpeg without some extra modules and setup and stuff.

**Comment by AdityaTD** [comment]
Well... Kinda an update, it works from time to time, like it was working in June but now it's not working again, idk what the issue is with this Search thing....

**Comment by Snarr** [comment]
I can confirm that this issue is still relevant. I get this error when I try to search:

```
{ Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at exports.execFile (child_process.js:143:15)
    at call (/home/snarrbot/node_modules/youtube-dl/lib/youtube-dl.js:161:3)
    at Function.getInfo (/home/snarrbot/node_modules/youtube-dl/lib/youtube-dl.js:274:3)
    at msg.channel.sendMessage.then.response (/home/snarrbot/node_modules/discord.js-music-v11/index.js:160:14)
    at process._tickCallback (internal/process/next_tick.js:109:7) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```

**Comment by AdityaTD** [comment]
Okay, mark this issue as solved as updating **youtube-dl** to latest version fixed the search problem. It's nothing related to this code, it's basically the dependencies.
